#ifndef LOV_TOKENS_H
#define LOV_TOKENS_H

#define LOV_MAX_TOKEN_SIZE (512U)
#define LOV_MAX_STRTOK_SIZE (4096U)

#define LOV_MAX_TOKEN_COUNT (8192U)
#define LOV_MAX_STRTOK_COUNT (1024U)

#define LOV_CHAR_COLON (0x3A)
#define LOV_CHAR_SEMICOLON (0x3B)
#define LOV_CHAR_EQUALS (0x3D)
#define LOV_CHAR_SPACE (0x20)
#define LOV_CHAR_HTAB (0x09)
#define LOV_CHAR_CR (0x0D)
#define LOV_CHAR_LF (0x0A)
#define LOV_CHAR_LPAREN (0x28)
#define LOV_CHAR_RPAREN (0x29)
#define LOV_CHAR_DBLQUOTE (0x22)
#define LOV_CHAR_HYPHEN (0x2D)
#define LOV_CHAR_MINUS LOV_CHAR_HYPHEN
#define LOV_CHAR_COMMA (0x2C)
#define LOV_CHAR_DOT (0x2E)
#define LOV_CHAR_PLUS (0x2B)
#define LOV_CHAR_ASTERISK (0x2A)
#define LOV_CHAR_SLASH (0x2F)
#define LOV_CHAR_LT (0x3C)
#define LOV_CHAR_OABRACKET LOV_CHAR_LT
#define LOV_CHAR_GT (0x3E)
#define LOV_CHAR_CABRACKET LOV_CHAR_GT
#define LOV_CHAR_AMPERSAND (0x26)

/* Token separators */
#define LOV_TSCHAR_COLON LOV_CHAR_COLON
#define LOV_TSCHAR_SEMICOLON LOV_CHAR_SEMICOLON
#define LOV_TSCHAR_SPACE LOV_CHAR_SPACE
#define LOV_TSCHAR_HTAB LOV_CHAR_HTAB
#define LOV_TSCHAR_CR LOV_CHAR_CR
#define LOV_TSCHAR_LF LOV_CHAR_LF
#define LOV_TSCHAR_LPAREN LOV_CHAR_LPAREN
#define LOV_TSCHAR_RPAREN LOV_CHAR_RPAREN
#define LOV_TSCHAR_HYPHEN LOV_CHAR_HYPHEN
#define LOV_TSCHAR_COMMA LOV_CHAR_COMMA
#define LOV_TSCHAR_DOT LOV_CHAR_DOT
#define LOV_TSCHAR_PLUS LOV_CHAR_PLUS
#define LOV_TSCHAR_ASTERISK LOV_CHAR_ASTERISK
#define LOV_TSCHAR_SLASH LOV_CHAR_SLASH
#define LOV_TSCHAR_LT LOV_CHAR_LT
#define LOV_TSCHAR_GT LOV_CHAR_GT
#define LOV_TSCHAR_AMPERSAND LOV_CHAR_AMPERSAND

/* Ignored characters */
#define LOV_ICHAR_SPACE LOV_CHAR_SPACE
#define LOV_ICHAR_HTAB LOV_CHAR_HTAB
#define LOV_ICHAR_CR LOV_CHAR_CR
#define LOV_ICHAR_LF LOV_CHAR_LF

/* Operators */
#define LOV_OP_NEQ ((LOV_CHAR_SLASH << 8) | LOV_CHAR_EQUALS)
#define LOV_OP_EQUAL LOV_CHAR_EQUALS
#define LOV_OP_LT LOV_CHAR_LT
#define LOV_OP_LTE ((LOV_CHAR_LT << 8) | LOV_CHAR_EQUALS)
#define LOV_OP_GT LOV_CHAR_GT
#define LOV_OP_GTE ((LOV_CHAR_GT << 8) | LOV_CHAR_EQUALS)
#define LOV_OP_CONCAT LOV_CHAR_AMPERSAND
#define LOV_OP_PLUS LOV_CHAR_PLUS
#define LOV_OP_MINUS LOV_CHAR_MINUS
#define LOV_OP_MUL LOV_CHAR_ASTERISK
#define LOV_OP_DIV LOV_CHAR_SLASH
#define LOV_OP_POW ((LOV_CHAR_ASTERISK << 8) | LOV_CHAR_ASTERISK)


#define LOV_COMMENT_CHAR_SEQ "--"

#endif /* LOV_TOKENS_H */
